# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "development" , "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
    
    - name: Run golangci-lint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: './backend'

    - name: Test
      run: |
        cd backend
        make test
    
    - name: Run go fmt
      run: |
        cd backend
        make format


    - name: Test
      run: make test

    
    

    